apiVersion: v1
kind: Secret
metadata:
    name: github-access
    namespace: default
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:llUgfMHU9QGto5+mT1TtAm0J,iv:lJsZkCskarlU2CaaVGoKxvfZ3/a7F39bFJ+lE/wLTAA=,tag:45Upa0/mEAjaOCy9njzilA==,type:str]
    username: ENC[AES256_GCM,data:SSItkQA=,iv:FQXhqJcKTIRioKggTGFIlcSZHr1NZJm9iWqugNBUkYI=,tag:6VVbzvGVOG4fE46MaPq7vQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:520385366554:key/25320ca7-4248-47d1-8661-2e60354db082
          created_at: "2023-10-16T08:59:42Z"
          enc: AQICAHhmEsvZDO+xUUCu3dcJsdcGRkB8gGoeS2xDAevXXhaQwgExpBfDydW+5Fspk9xihRKYAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMn434oKbAd4xomtAzAgEQgDv8Iv0bcJ3p85ZXezn3pNf76Q/cEkayIhwwfFlJDACoZL7WsqgzNEEDf3JxBDfZpGeELzzxb9Bounw5MQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-16T09:21:06Z"
    mac: ENC[AES256_GCM,data:gnN4JbaNP8ptZ4y6IMBf+DknFI2wC3xl+Gs+jmF/nYefAlsnnlxZ4WbrqLN4FkTkTbEGm2DD9VT+B312wNY353lJKx3628YHX4diInlQwNRVucrvaaskeRRKCW32pQu3xFDzwqKk4UgsUf+TfdCC0d1gWh+2HSoGv83CaunCwVc=,iv:KXbQKqZ25+gOzChnnigCV96/tQ+DhGruRHaeZB6J8LQ=,tag:8jFgsi1DOsBA2/B6q8U14A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
